#' Visualize T-test Power for Traditional vs. Pooling Study Design
#'
#' Useful for determining potential cost savings of a pooling study design.
#'
#'
#' @param delta Numeric value.
#' @param var Numeric value specifying variance of observations.
#' @param var_pe Numeric value specifying variance of additive processing error.
#' @param var_me Numeric value specifying variance of additive measurement
#' error.
#' @param type Character string specifying type of t-test. Choices are
#' \code{"two.sample"}, \code{"one.sample"}, and \code{"paired"}.
#' @param assay_cost Numeric value specifying cost of each assay.
#' @param other_costs Numeric value specifying other per-subject costs.
#' @param pool_size Numeric vector specifying pool sizes.
#' @param labels Logical value for whether to label data points corresponding to
#' 80\% power.
#' @param ... Arguments to pass to \code{\link[stats]{power.t.test}}.
#'
#'
#' @return Plot of power vs. total costs generated by
#' \code{\link[ggplot2]{ggplot}}.
#'
#'
#' @examples
#' # Power for two-sample t-test with delta = 0.5, var = 1, and no "other" costs
#' # per subject
#' poolpower_t(delta = 0.5, var = 1)
#'
#' # Repeat but for other costs per subject equal to 1/4 the assay cost
#' poolpower_t(delta = 0.5, var = 1, other_costs = 1/4)
#'
#' # Back to no other costs, but with processing and measurement error
#' poolpower_t(delta = 0.5, var = 1, var_pe = 0.2, var_me = 0.1)
#'
#'
#'@export
poolpower_t <- function(delta = 0.5,
                        var = 1,
                        var_pe = 0,
                        var_me = 0,
                        type = "two.sample",
                        assay_cost = 1,
                        other_costs = 0,
                        pool_size = c(1, 2, 3, 10),
                        labels = TRUE,
                        ...) {

  # Create vector from 2 to sample size needed for 99.9% power
  n.assays <- 2: ceiling(power.t.test(delta = delta,
                                      sd = sqrt(var),
                                      type = type,
                                      power = 0.999, ...)$n)

  # Create data frame with variables to plot
  df <- NULL
  for (ii in pool_size) {

    n.subjects <- n.assays * ii
    costs <- n.assays * assay_cost + n.subjects * other_costs
    power <- power.t.test(n = n.assays,
                          delta = delta,
                          sd = sqrt(var / ii + var_me + var_pe * (ii > 1)),
                          type = type, ...)$power
    power_80 <- rep(0, length(n.assays))
    power_80[which(power >= 0.8)[1]] <- 1
    df <- bind_rows(df, data.frame(g = ii,
                                   n.assays = n.assays,
                                   costs = costs,
                                   power = power,
                                   power_80 = power_80))

  }

  # Exclude values with power > 99.9
  df <- subset(df, power <= 0.999)

  # Create plot
  p <- ggplot(df, aes(costs, power, group = g, color = as.factor(g))) +
    geom_point() +
    geom_line() +
    labs(title = "Power vs. Total Study Costs",
         y = "Power",
         x = "Study costs",
         color = "Pool size") +
    geom_hline(yintercept = c(0, 0.5, 0.8, 0.9, 1), linetype = 2) +
    theme_bw() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    scale_y_continuous(breaks = c(0, 0.5, 0.8, 0.9, 1))

  # Label points with 80% power
  if (labels) {
    p <- p + geom_label_repel(
      data = subset(df, power_80 == 1),
      aes(costs, power, label = paste(
        "$", costs, " (", n.assays, " assays)", sep = "")),
      color = "black",
      box.padding = 0.5, point.padding = 0.3)
  }
  p

}
