#' Visualize T-test Power for Pooling Design
#'
#' Useful for assessing efficiency gains that might be achieved with a pooling
#' design.
#'
#'
#' @param g Numeric vector of pool sizes to include.
#' @param d Numeric value specifying true difference in group means. Only used
#' if \code{multiplicative = FALSE}.
#' @param sigsq Numeric value specifying the variance of observations.
#' @param sigsq_p Numeric value specifying the variance of processing errors.
#' @param sigsq_m Numeric value specifying the variance of measurement errors.
#' @param multiplicative Logical value for whether to assume multiplicative
#' rather than additive errors.
#' @param mu1,mu2 Numeric value specifying group means. Only used if
#' \code{multiplicative = TRUE}.
#' @param alpha Numeric value specifying type-1 error rate.
#' @param beta Numeric value specifying type-2 error rate.
#' @param assay_cost Numeric value specifying cost of each assay.
#' @param other_costs Numeric value specifying other per-subject costs.
#' @param labels Logical value.
#' @param ylim Numeric vector.
#'
#'
#' @return Plot of power vs. total costs generated by
#' \code{\link[ggplot2]{ggplot}}.
#'
#'
#' @examples
#' # Plot power vs. total study costs for d = 0.25, sigsq = 1, and costs of $100
#' # per assay and $0 in other per-subject costs.
#' poolpower_t(d = 0.5, sigsq = 1, assay_cost = 100, other_costs = 0)
#'
#' # Repeat but with $10 in per-subject costs.
#' poolpower_t(d = 0.5, sigsq = 1, assay_cost = 100, other_costs = 10)
#'
#' # Back to no per-subject costs, but with processing and measurement error
#' poolpower_t(d = 0.5, sigsq = 1, sigsq_p = 0.2, sigsq_m = 0.1,
#'             assay_cost = 100, other_costs = 0)
#'
#'
#'@export
poolpower_t <- function(g = c(1, 3, 10),
                        d = NULL,
                        sigsq,
                        sigsq_p = 0,
                        sigsq_m = 0,
                        multiplicative = FALSE,
                        mu1 = NULL,
                        mu2 = NULL,
                        alpha = 0.05,
                        beta = 0.2,
                        assay_cost = 100,
                        other_costs = 0,
                        labels = TRUE,
                        ylim = NULL) {

  # Create vector from 3 to assays per group for 99.9% power with traditional
  # design
  n <- 3: ceiling(2 * (qnorm(0.999) + qnorm(1 - alpha / 2))^2 /
                    d^2 * (sigsq + sigsq_m))

  # Calculate power vs. n.pergroup for each pool size
  if (! multiplicative) {

    df <- dvmisc::power_2t_equal %>% dvmisc::iterate(
      d = d,
      sigsq = sigsq / g + sigsq_p * ifelse(g > 1, 1, 0) + sigsq_m,
      n = n,
      alpha = alpha,
      varnames = "power"
    )

  } else {

    sigsq_pm <- sigsq_m + sigsq_p * (1 + sigsq_m) * ifelse(g > 1, 1, 0)
    df <- dvmisc::power_2t_unequal %>% dvmisc::iterate(
      d = d,
      sigsq1 = sigsq_pm * (mu1^2 + sigsq / g) + sigsq / g,
      sigsq2 = sigsq_pm * (mu2^2 + sigsq / g) + sigsq / g,
      n = n,
      alpha = alpha
    )

  }

  # Prep for ggplot
  df$g <- rep(g, each = length(n))
  df$n.assays <- df$n * 2
  df$n.subjects <- df$g * df$n.assays
  df$costs <- df$n.assays * assay_cost + df$n.subjects * other_costs
  df$power.lab <- c(0, ifelse(diff(sign(df$power - (1 - beta))) >= 1, 1, 0))

  # Exclude values with power > 99.9%
  df <- df %>% dplyr::filter(power <= 0.999)

  # Create labels
  if (all(df$costs[df$power.lab == 1] > 1000)) {
    df$costs <- df$costs / 1000
    df$costlabel <- paste("$", df$costs, "k (", df$n.assays, " total assays)", sep = "")
    dollar.units <- "($1,000)"
  } else {
    df$costlabel <- paste("$", df$costs, " (", df$n.assays, " total assays)", sep = "")
    dollar.units <- "($)"
  }

  # Create plot
  costs <- NULL
  p <- ggplot(df, aes(costs, power, group = g, color = as.factor(g))) +
    geom_point() +
    geom_line() +
    labs(title = "Power vs. Total Study Costs",
         y = "Power",
         x = paste("Study costs", dollar.units),
         color = "Pool size") +
    geom_hline(yintercept = unique(c(0, 0.5, 1 - beta, 1)), linetype = 2) +
    theme_bw() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    scale_y_continuous(breaks = unique(c(0, 0.5, 1 - beta, 1)))

  # Label points with sufficient power
  if (labels) {
    power.lab <- NULL
    p <- p + geom_label_repel(
      data = subset(df, power.lab == 1),
      aes_string(x = "costs", y = "power", label = "costlabel"),
      box.padding = 0.5, point.padding = 0.3,
      show.legend = FALSE)
  }
  p

}
