#' Visualize Ratio of Variance of Each Pooled Measurement to Variance of Each
#' Unpooled Measurement as Function of Pool Size
#'
#' Useful for determining whether pooling is a good idea, and finding the
#' optimal pool size if it is.
#'
#'
#' @param g Numeric vector of pool sizes to include.
#' @param var Numeric value specifying variance of observations.
#' @param var_pe Numeric value specifying variance of additive processing error.
#' @param var_me Numeric value specifying variance of additive measurement
#' error.
#' @param type Character string specifying type of t-test. Choices are
#' \code{"two.sample"}, \code{"one.sample"}, and \code{"paired"}.
#' @param assay_cost Numeric value specifying cost of each assay.
#' @param other_costs Numeric value specifying other per-subject costs.
#' @param label_max Logical value.
#' @param ... Arguments to pass to \code{\link[stats]{power.t.test}}.
#'
#'
#' @return Plot of power vs. total costs generated by
#' \code{\link[ggplot2]{ggplot}}.
#'
#'
#'@export
poolvar_t <- function(g = 1: 50,
                      var = 1,
                      var_pe = 0,
                      var_me = 0,
                      type = "two.sample",
                      assay_cost = 1,
                      other_costs = 0,
                      label_max = TRUE,
                      ylim = NULL,
                      ...) {

  # Create data frame with variables to plot
  var_ratio <- (var + var_me) / (var / g + var_pe + var_me) /
    ((assay_cost + g * other_costs) / (assay_cost + other_costs))
  df <- data.frame(g = g, var_ratio = var_ratio)
  df$max <- 0
  df$max[which.max(df$var_ratio)] <- 1

  # Create plot
  p <- ggplot(df, aes(g, var_ratio)) +
    geom_point() +
    labs(title = "Ratio of Variances, Traditional vs. Pooled",
         y = "Ratio",
         x = "Pool size") +
    geom_hline(yintercept = 1, linetype = 2) +
    theme_bw() +
    theme(legend.title=element_blank())

  # Label max
  if (label_max) {
    p <- p + geom_label_repel(
      data = subset(df, max == 1),
      aes(g, var_ratio, label = paste(
        "g = ", g, ", ratio = ", round(var_ratio, 1), sep = "")),
      color = "black", box.padding = 0.75, point.padding = 0.3
    )
  }

  # Adjust ylim
  if (! is.null(ylim)) {
    p <- p + ylim(ylim)
  }
  p

}

# poolvar_t <- function(var = 1,
#                       var_pe = 0,
#                       var_me = 0,
#                       type = "two.sample",
#                       assay_cost = 1,
#                       other_costs = 0,
#                       label_max = TRUE,
#                         ...) {
#
#   # Create data frame with variables to plot
#   g <- 1: 50
#   var_ratio <- (var + var_me) / (var / g + var_pe + var_me)
#   max <- rep(0, length(g))
#   max[which.max(var_ratio)] <- 1
#   df <- data.frame(g = g, adjusted = 0, var_ratio = var_ratio, max = max)
#   if (other_costs > 0) {
#     var_ratio <- var_ratio / ((assay_cost + g * other_costs) / (assay_cost + other_costs))
#     df <- df %>% bind_rows(
#       data.frame(g = g, adjusted = 1, var_ratio = var_ratio, max = max)
#     )
#   }
#   df$adjusted <- factor(df$adjusted, levels = c(0, 1), labels = c("Unadjusted", "Adjusted for other costs"))
#
#   # Create plot
#   p <- ggplot(df, aes(g, var_ratio, color = adjusted)) +
#     geom_point(show.legend = assay_cost > 0) +
#     labs(title = "Ratio of Variances, Traditional vs. Pooled",
#          y = "Ratio",
#          x = "Pool size") +
#     geom_hline(yintercept = 1, linetype = 2) +
#     theme_bw() +
#     theme(legend.title=element_blank())
#   p
#
#   # Label point(s) where ratio is maximized
#   if (label_max) {
#     p <- p + geom_label_repel(
#       data = subset(df, max == 1),
#       aes(g, var_ratio, label = paste(
#         "g = ", g, ", ratio = ", round(var_ratio, 1), sep = "")),
#       color = "black", box.padding = 0.75, point.padding = 0.3
#       )
#   }
#   p
#
# }
